config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

#urlpatterns = [path("<int:pk>", views.room_detail, name="detail")]
urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.search, name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models
from users import models as user_models #users의 앱(패키지) 사용
#def __str__ 사용하는 이유 https://neung0.tistory.com/51 참고


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """
    name = models.CharField(max_length=80)
    class Meta:
        abstract = True

    def __str__(self):
        return self.name

class RoomType(AbstractItem):

    """ RoomType Object Definition"""
    
    class Meta:
        verbose_name = "Room Type"
        ordering = ['name']
    

class Amenity(AbstractItem):

    """ RoomType Object Definition """
    class Meta:
        verbose_name_plural = 'Amenities'


class Facility(AbstractItem):

    """ Facility Model Definition """
    class Meta:
        verbose_name_plural = 'Facilities'
    

class HouseRule(AbstractItem):

    """ HouseRule MOdel Definition"""

    class Meta:
        verbose_name = "House Rule"

class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    caption = models.CharField(max_length = 80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE) #방을 지우면 사진도 같이 삭제되도록

    def __str__(self):
        return self.caption



# Create your models here.
class Room(core_models.TimeStampedModel):

    """ Room Model Definition """

    name = models.CharField(max_length=150)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=90)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default = False)
    host = models.ForeignKey("users.User", related_name = "rooms", on_delete=models.CASCADE)#users 폴더의 user
    room_type = models.ForeignKey("RoomType", related_name = "rooms", blank=True, on_delete=models.SET_NULL, null = True)
    #1 User, Many Rooms
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)


    def __str__(self):
        return self.name

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews))
        return 0

    #admin 패널에서 바로 프론트엔드 부분으로
    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs = {'pk':self.pk})

rooms/views.py
from django.views.generic import ListView, DetailView
from django.http import Http404
from django.urls import reverse
from django.shortcuts import render, redirect
from django_countries import countries
from . import models


class HomeView(ListView):
    """ HomeView Definition """
    model = models.Room
    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


# def room_detail(request, pk):
#     try:
#         room = models.Room.objects.get(pk=pk)
#         return render(request, "rooms/detail.html", {'room' : room})
#     except models.Room.DoesNotExist:
#         #return redirect(reverse("core:home"))
#         raise Http404()

class RoomDetail(DetailView):
    """ 
    RoomDetail Definition 
    - HomeView 위에서 보듯이 반드시 view가 볼 model에 대해서 먼저 지정해주어야 함.
    """
    model = models.Room


def search(request):
    city = request.GET.get("city", "Anywhere")
    city = str.capitalize(city)
    country = request.GET.get("country", "KR")
    room_type = int(request.GET.get("room_type", 0))
    price = int(request.GET.get("price", 0))
    guests = int(request.GET.get("guests", 0))
    bedrooms = int(request.GET.get("bedrooms", 0))
    beds = int(request.GET.get("beds", 0))
    baths = int(request.GET.get("baths", 0))
    s_amenities = request.GET.get("amenities")
    s_facilities = request.GET.get("facilities")
    
    
    form = {
        "city": city,
        "s_room_type": room_type,
        "s_country": country,
        "price": price,
        "guests": guests,
        "bedrooms": bedrooms,
        "beds": beds,
        "baths": baths,
    }

    room_types = models.RoomType.objects.all()
    amenities = models.Amenity.objects.all()
    facilities = models.Facility.objects.all()

    choices = {
        "countries": countries,
        "room_types": room_types,
        "amenities": amenities,
        "facilities": facilities,
    }

    return render(request, "rooms/search.html", {**form, **choices})
    # {"city" : city}는 context를 의미함. context는 현재파일인 views.py에서 변수로 사용한 city 변수를 html 변수로 넘기는 것을 의미함
    # render 함수 = template인 html파일을 화면에 띄워줌
    # 파리미터 = request, template, 
    # countries변수는 django.countries 라이브러리에서 가져왔음

templates/rooms/detail.html
{% extends "base.html" %}


{% block page_name %}
    Home
{% endblock page_name %}

{% block content %}
<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
    <h3>$ {{room.price}}</h3>
</div>

<div>
    <h2>By: {{room.host.username}} 
    {% if room.host.superhost %}
        (superhost)
    {% endif %}
    </h2>
    <h3>
        Amenities
    </h3>
    <ul>
    {%for a in room.amenities.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>
        Facilities
    </h3>
    <ul>
    {%for a in room.facilities.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>
        House Rules
    </h3>
    <ul>
    {%for a in room.house_rules.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

templates/rooms/room_detail.html
{% extends "base.html" %}


{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}
<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
    <h3>$ {{room.price}}</h3>
</div>

<div>
    <h2>By: {{room.host.username}} 
    {% if room.host.superhost %}
        (superhost)
    {% endif %}
    </h2>
    <h3>
        Amenities
    </h3>
    <ul>
    {%for a in room.amenities.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>
        Facilities
    </h3>
    <ul>
    {%for a in room.facilities.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>
        House Rules
    </h3>
    <ul>
    {%for a in room.house_rules.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

templates/rooms/room_list.html
{% extends "base.html" %}


{% block page_name %}
    Home 
{% endblock page_name %}

{% block content %}

    {{now}}
    
    {% for room in rooms  %}
        <h3>
            <a href="{% url "rooms:detail" room.pk %}">
                {{room.name}} / ${{room.price}}
            </a>
        </h3>
    {% endfor %}

    <h5>
    {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}

    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

    {% if page_obj.has_next  %}
        <a href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}


    </h5>


{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <h2>Search!</h2>

    <form method="get" action="{% url "rooms:search" %}">
        <div>
            <label for="city">City</label>
            <input value="{{city}}" id="city" name="city" placeholder="Search By City" />
        </div>

        <div>
            <label for="country">Country</label>
            <select id="country" name="country" >
                {% for country in countries  %}
                    <option value="{{country.code}}" {% if country.code == s_country  %}selected{% endif %}>{{country.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="room_type">Room Type</label>
            <select id="room_type" name="room_type">
                <option value="0" {% if s_room_type == 0  %}selected{% endif %}>Any kind</option>
                {% for room_type in room_types  %}
                    <option value="{{room_type.pk}}" {% if s_room_type == room_type.pk  %}selected{% endif %}>{{room_type.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="price">Price</label>
            <input value="{{price}}" type="number" name="price" id="price" placeholder="Price" />
        </div>

        <div>
            <label for="guests">Guests</label>
            <input value="{{guests}}" type="number" name="guests" id="guests" placeholder="Guests" />
        </div>

        <div>
            <label for="bedrooms">Bedrooms</label>
            <input value="{{bedrooms}}" type="number" name="bedrooms" id="bedrooms" placeholder="Bedrooms" />
        </div>

        <div>
            <label for="beds">Beds</label>
            <input value="{{beds}}" type="number" name="beds" id="beds" placeholder="Beds" />
        </div>

        <div>
            <label for="baths">Baths</label>
            <input value="{{baths}}" type="number" name="baths" id="baths" placeholder="Baths" />
        </div>

        <div>
            <h3>Amenities</h3>
            <ul>
                {% for amenity in amenities %}
                    <li>
                        <label for="a_{{amenity.pk}}">{{amenity.name}}</label>
                        <input id="a_{{amenity.pk}}" name="amenities" type="checkbox" value={{amenity.pk}} />
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div>
            <h3>Facilities</h3>
            <ul>
                {% for facility in facilities %}
                    <li>
                        <label for="f_{{facility.pk}}">{{facility.name}}</label>
                        <input id="f_{{facility.pk}}" name="facilities" type="checkbox" value={{facility.pk}} />
                    </li>
                {% endfor %}
            </ul>
        </div>
        <button>Search</button>
    </form>



{% endblock content %}